version: '3.2'
services:
  composer:
    build: .
    # image: cozzz/swoole:7.2-sqlsrv
    volumes:
      - ../../www/:/app/:rw
      - ./conf/:/usr/local/etc/php/:rw
    restart: always
    stdin_open: true
    tty: true
